[workspace]
members = [
    "lib",
    "bin",
]

[workspace.dependencies]
rsa = { version = "0.9.6", features = ["serde", "sha2"] }
serde = { version = "1.0.202", features = ["derive"] }
num-bigint = { version = "0.4.5", features = ["serde"] }
rand = "0.8.5"