[package]
name = "shareholder_crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-literal = "0.4.1"
num-bigint = "0.4.5"
num-prime = "0.4.3"
rand = "0.8.5"
sha256 = "1.5.0"

